const $=id=>document.getElementById(id);let categories=[],current=[],selected=-1,activeCategory='';
const viewer=$('viewer');
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
function photo(item){const wrap=el('div','photo');const img=el('img');img.src=item.src;img.alt=item.name;img.loading='lazy';img.decoding='async';wrap.append(img);return wrap;}
function render(){let name='';try{name=decodeURIComponent(location.hash.slice(1));}catch{}const category=categories.find(c=>c.name===name);activeCategory=category?.name||'';document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.dataset.category===activeCategory?'page':'false'));$('heading').textContent=category?category.name:'แคตตาล็อกสินค้า';$('count').textContent=category?`${category.items.length.toLocaleString('th')} รูปสินค้า`:`${categories.length} หมวด · ${categories.reduce((n,c)=>n+c.items.length,0).toLocaleString('th')} รูปสินค้า`;$('content').replaceChildren();const grid=el('div','grid');$('content').append(grid);current=category?.items||[];
if(category){if(!current.length)grid.append(el('p','empty','ยังไม่มีสินค้าในหมวดนี้'));current.forEach((item,i)=>{const card=el('button','card');card.type='button';card.append(photo(item),el('span','card-title',item.name));card.setAttribute('aria-label',`ดูรูป ${item.name}`);card.addEventListener('click',()=>openImage(i));grid.append(card);});}else{for(const c of categories){const card=el('a','card category-card');card.href='#'+encodeURIComponent(c.name);if(c.items.length){const p=photo(c.items[0]);p.classList.add('category-photo');card.append(p);}const title=el('span','card-title',c.name);title.append(el('b',null,'↗'));card.append(title,el('span','card-meta',`${c.items.length} รูปสินค้า`));grid.append(card);}}}
function openImage(i){selected=i;const item=current[i];$('full-image').src=item.src;$('full-image').alt=item.name;$('image-name').textContent=item.name;$('image-category').textContent=activeCategory;$('position').textContent=`${i+1} / ${current.length}`;$('previous').disabled=i===0;$('next').disabled=i===current.length-1;if(!viewer.open)viewer.showModal();}
$('close').onclick=()=>viewer.close();$('previous').onclick=()=>selected>0&&openImage(selected-1);$('next').onclick=()=>selected<current.length-1&&openImage(selected+1);viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close();}});document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowLeft'&&selected>0)openImage(selected-1);if(e.key==='ArrowRight'&&selected<current.length-1)openImage(selected+1);});window.addEventListener('hashchange',()=>{viewer.close();render();window.scrollTo(0,0);});
async function init(){try{const response=await fetch('catalog.json');if(!response.ok)throw Error('Catalog unavailable');categories=await response.json();$('category-count').textContent=categories.length;for(const c of [{name:'',label:'ทั้งหมด'},...categories]){const a=el('a',null,c.label||c.name);a.href=c.name?'#'+encodeURIComponent(c.name):'#';a.dataset.category=c.name;if(c.items)a.append(el('span',null,String(c.items.length)));$('categories').append(a);}render();}catch{$('count').textContent='';const message=el('p','empty','โหลดรายการสินค้าไม่สำเร็จ กรุณาลองใหม่');const retry=el('button',null,'ลองใหม่');retry.onclick=()=>location.reload();$('content').replaceChildren(message,retry);}}init();
